services:
  bt-util:
    build:
      context: ./
      dockerfile: "Dockerfile.bt_util"
    image: "monkey/humble:bt_util"
    command: /bin/bash
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /root/dep_ws/src/
    #       ignore:
    #         - node_modules/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    privileged: true
    # cap_add:
    #   - ALL
    #runtime: nvidia # GPU
    environment:
      # Displays
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LIB_GL_ALWAYS_INDIRECT=0
      - XAUTHORITY=/tmp/.docker.xauth
      # GPU
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    user: "root"
    volumes:
      # Docker display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      # Copy Paste from Host
      - ./bt_util:/root/dep_ws/src/monkey_bt_util
      # Device
      - /dev:/dev
      