FROM monkey/humble:no-gpu

ARG HOME_DIR=/root
ARG ROS_DISTRO=humble

# Install packages 
RUN apt-get update \
    && apt-get install -y \
    python3-pip \
    cmake \
    libzmq3-dev \
    libboost-dev \
    ros-humble-behaviortree-cpp \
    # # For accessing low level I/O privileges
    # libcap-dev \ 
    && pip install python-can[serial] \
    jinja2 \
    typeguard \
    && rm -rf /var/lib/apt/lists/*

# Clone BTCPP and BTROS2 and build dep_ws
WORKDIR ${HOME_DIR}/dep_ws/src
COPY bt_util /root/dep_ws/src/monkey_bt_util
RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
    && git clone https://github.com/BehaviorTree/BehaviorTree.ROS2.git -b humble \
    && git clone https://github.com/PickNikRobotics/RSL.git \
    && git clone https://github.com/PickNikRobotics/cpp_polyfills.git\
    && git clone https://github.com/PickNikRobotics/generate_parameter_library.git \
    # Monkey BT Util
    # && git clone https://github.com/MonKey-Robotics/monkey_bt_util.git \
    && cd ${HOME_DIR}/dep_ws/ \
    && . /opt/ros/${ROS_DISTRO}/setup.sh \
    && colcon build --packages-ignore monkey_bt_util
# 

# Set up .bashrc scripts
RUN echo "source /root/dep_ws/install/setup.bash" >> /root/.bashrc

WORKDIR /root

CMD ["bash"]